bridge:
  # Port to host the bridge on
  # Used for communication between the homeserver and the bridge
  port: 8434
  # The host connections to the bridge's webserver are allowed from
  bindAddress: localhost
  # Public domain of the homeserver
  domain: matrix.org
  # Reachable URL of the Matrix homeserver
  homeserverUrl: https://matrix.org

presence:
  # Bridge Discord online/offline status
  enabled: true
  # How often to send status to the homeserver in milliseconds
  interval: 500

provisioning:
  # Regex of Matrix IDs allowed to use the puppet bridge
  whitelist:
    # Allow a specific user
    #- "@user:server\.com"
    # Allow users on a specific homeserver
    #- "@.*:yourserver\.com"
    # Allow anyone
    - ".*"
  # Regex of Matrix IDs forbidden from using the puppet bridge
  blacklist:
    # Disallow a specific user
    #- "@user:server\.com"
    # Disallow users on a specific homeserver
    #- "@.*:yourserver\.com"

database:
  # The name of the database file
  filename: database.db
